numpy:
- '1.14'
perl:
- '5.26'
lua:
- '5'
r_base:
- '3.5'
cpu_optimization_target:
- nocona
cran_mirror:
- https://mran.microsoft.com/snapshot/2018-01-01
target_platform:
- win-64
fortran_compiler:
- intel-fortran
cudatoolkit:
- '9.0'
r_implementation:
- r-base
- mro-base
noarch_python:
- python
apr:
- 1.6.3
blas_impl:
- mkl
boost:
- '1.67'
boost_cpp:
- '1.67'
bzip2:
- '1.0'
cairo:
- '1.14'
m2w64_c_compiler:
- m2w64-toolchain
m2w64_cxx_compiler:
- m2w64-toolchain
m2w64_fortran_compiler:
- m2w64-toolchain
rust_compiler:
- rust-gnu
- rust
rust_compiler_version:
- 1.40.0
VERBOSE_AT:
- V=1
VERBOSE_CM:
- VERBOSE=1
clang_variant:
- clang
cyrus_sasl:
- 2.1.26
dbus:
- '1'
expat:
- '2.2'
fontconfig:
- '2.13'
freetype:
- '2.10'
g2clib:
- '1.6'
gstreamer:
- '1.14'
gst_plugins_base:
- '1.14'
giflib:
- '5.1'
glib:
- '2'
gmp:
- '6.1'
gnu:
- 2.12.2
harfbuzz:
- '2.4'
hdf4:
- '4.2'
hdf5:
- 1.10.6
hdfeos2:
- '2.20'
hdfeos5:
- '5.1'
icu:
- '58'
jpeg:
- '9'
libdap4:
- '3.19'
libffi:
- '3.3'
libgd:
- 2.2.5
libgdal:
- '3.0'
libgsasl:
- '1.8'
libkml:
- '1.3'
libnetcdf:
- '4.6'
libpng:
- '1.6'
libtiff:
- '4.1'
libwebp:
- 1.0.0
libxml2:
- '2.9'
libxslt:
- '1.1'
llvm_variant:
- llvm
lzo:
- '2'
macos_min_version:
- '10.9'
macos_machine:
- x86_64-apple-darwin13.4.0
MACOSX_DEPLOYMENT_TARGET:
- '10.9'
mkl:
- '2019'
mpfr:
- '4'
openblas:
- 0.3.3
openjpeg:
- '2.3'
openssl:
- 1.1.1
pixman:
- '0.34'
proj4:
- 5.2.0
proj:
- 6.2.1
libprotobuf:
- 3.11.2
python_implementation:
- cpython
python_impl:
- cpython
r_version:
- 3.5.0
readline:
- '8.0'
serf:
- 1.3.9
sqlite:
- '3'
cross_compiler_target_platform:
- win-32
- win-64
tk:
- '8.6'
zlib:
- '1.2'
xz:
- '5'
qtwebkit:
- 'true'
channel_targets:
- defaults
extend_keys:
- extend_keys
- pin_run_as_build
- ignore_build_only_deps
- ignore_version
cxx_compiler:
- vs2017
- vs2017
- vs2017
vc:
- '14'
- '14'
- '14'
geos:
- 3.8.0
- 3.8.0
- 3.8.0
python:
- '3.8'
- '3.7'
- '3.6'
nodejs:
- '8.12'
- '8.12'
- '8.12'
fortran_compiler_version:
- 2019.0.0
- 2019.0.0
- 2019.0.0
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    max_pin: x.x
    min_pin: x.x
  libboost:
    max_pin: x.x.x
ignore_build_only_deps:
- numpy
- python
c_compiler:
- vs2017
- vs2017
- vs2017
zip_keys:
- - vc
  - c_compiler
  - cxx_compiler
  - fortran_compiler_version
  - python
  - nodejs
  - geos
